"""empty message

Revision ID: 228ca7fe1527
Revises: 733b497d6269
Create Date: 2020-09-23 12:19:44.385671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228ca7fe1527'
down_revision = '733b497d6269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caso')
    # ### end Alembic commands ###
