"""empty message

Revision ID: 44155614eab6
Revises: 
Create Date: 2020-11-08 23:25:22.033211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44155614eab6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escritorio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_fantasia', sa.String(length=250), nullable=False),
    sa.Column('razao_social', sa.String(length=250), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('n_oab', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('n_oab'),
    sa.UniqueConstraint('nome_fantasia'),
    sa.UniqueConstraint('razao_social')
    )
    op.create_table('pesquisa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_site', sa.String(length=50), nullable=False),
    sa.Column('atalho', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('caso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caso')
    op.drop_table('usuario')
    op.drop_table('pesquisa')
    op.drop_table('escritorio')
    # ### end Alembic commands ###
