"""empty message

Revision ID: 599dccb63bbd
Revises: 47b6c146859c
Create Date: 2020-09-27 21:30:51.620620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599dccb63bbd'
down_revision = '47b6c146859c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escritorio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razao_social', sa.String(length=250), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('n_oab', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('criado_em', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('n_oab'),
    sa.UniqueConstraint('razao_social')
    )
    op.create_table('caso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caso')
    op.drop_table('escritorio')
    # ### end Alembic commands ###
