"""empty message

Revision ID: f9d7fdf0eb1b
Revises: 599dccb63bbd
Create Date: 2020-10-04 19:51:49.607165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d7fdf0eb1b'
down_revision = '599dccb63bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesquisa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_site', sa.String(length=50), nullable=False),
    sa.Column('atalho', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pesquisa')
    # ### end Alembic commands ###
